### ISSUE TITLE
pg_class relpartbound breaks PG 9.6

### ISSUE THREAD

**Issue by David-Keeffe** [djrobstep/schemainspect#28]
The now-closed but unresolved issue raised earlier about pg_catalog.pg_class.relpartbound means that I can't use this with PG9.6.
Is there any plan to fix this?

**Comment by djrobstep** [comment]
We now have a dedicated test run for pg9 (albeit with some skipped tests), they pass so this should be fixed now.

I would still suggest upgrading if possible as v9 will always get the least dev attention and test coverage.
