### ISSUE TITLE
empty string vs null in misc::quoted_identifiers

### ISSUE THREAD

**Issue by Iced-Sun** [djrobstep/schemainspect#31]
Since both empty string and `None` will be evaluated as `False` in python, the [line](https://github.com/djrobstep/schemainspect/blob/b8cf64f4008b3c39c5143a5a53a18ae9b1c62ccc/schemainspect/misc.py#L38) `if identity_arguments:` will mis-produce a result of`schema.func` instead of `schema.func()` for a function without  any arguments.

Changing the corresponding line to `if identity_arguments is not None:` will be a quick fix.

Thank you!

**Comment by djrobstep** [comment]
Thanks for reporting this, this is finally fixed as of the latest release!
