### ISSUE TITLE
Use uppercase SQL keywords

### ISSUE THREAD

**Issue by ThiefMaster** [djrobstep/schemainspect#42]
In most places, SQL keywords such as CREATE DROP, etc. are written in uppercase. Would you accept a PR that changes the output of this library accordingly?

**Comment by djrobstep** [comment]
Personally, I dislike the uppercase syntax (purely for aesthetic reasons) and so I implemented this library using lowercase (which Postgres is fine with).

I wouldn't accept a PR changing this unless it made both uppercase and lowercase available as options (which would be a lot of changes and extra complexity).
