### ISSUE TITLE
Tables with zero columns not reported

### ISSUE THREAD

**Issue by djrobstep** [djrobstep/schemainspect#5]
As reported in https://github.com/djrobstep/migra/issues/22, schemainspect doesn't currently detect tables with zero columns.

**Comment by jflambert** [comment]
Well, as a new migra user this threw me for a loop. Spent a solid hour trying to figure out what I was doing wrong! So here's a vote to fixing this issue.

**Comment by djrobstep** [comment]
Yep it would be good to get this fixed.. I'm a bit time-poor at the moment so won't be happening immediately, but in the meantime I'd welcome pull requests.

Why do you have zero-column tables in your database, out of curiosity? Is there a practical use for these?

**Comment by jflambert** [comment]
No, empty tables are not a common use case. It's literally just the first thing I thought to do when testing your tool. If I had added a column or renamed a table I wouldn't be here ;)

**Comment by djrobstep** [comment]
Fixed this as of latest release.
