### ISSUE TITLE
KeyError when loading relations from Timescale DB

### ISSUE THREAD

**Issue by spoykko** [djrobstep/schemainspect#55]
Hi,
Running schemainspect against PostgreSQL with a TimeScale extension results in error.
I believe this could be caused by indexes pointing to extension tables.
The default logic seems to skip extension tables from the relations collection at load_all_relations but will still try to load the indexes.
I'll attach an output of test done against a fresh [Docker image of Timescale](https://docs.timescale.com/latest/getting-started/installation/docker/installation-docker): 

[fail_at_test_indexes.txt](https://github.com/djrobstep/schemainspect/files/5309008/fail_at_test_indexes.txt)
Samuli

**Comment by djrobstep** [comment]
Thanks for this. The logic changed for this in a recent PR, which caused some regressions in extension detection :(

Reviewing your PR now, looks good. Should be able to merge shortly.

**Comment by spoykko** [comment]
Good to have this merged! Thank you for your attention and efforts!
