### ISSUE TITLE
Exception when inspecting a view that uses the PostGIS ST_Dump() function

### ISSUE THREAD

**Issue by trendels** [djrobstep/schemainspect#59]
I've encountered this bug when using migra against a database that contains views that use the PostGIS function [`ST_Dump()`][1].

Minimal SQL schema to reproduce:

    create extension postgis;
    create table t (geom geometry);
    create view v as select (ST_Dump(geom)).geom from t;

<details>
<summary>Traceback:</summary>
<pre>
$ migra postgres:///a postgres:///b
Traceback (most recent call last):
  File "/home/st/p/python/migra/venv/bin/migra", line 8, in <module>
    sys.exit(do_command())
  File "/home/st/p/python/migra/venv/lib/python3.8/site-packages/migra/command.py", line 108, in do_command
    status = run(args)
  File "/home/st/p/python/migra/venv/lib/python3.8/site-packages/migra/command.py", line 79, in run
    m = Migration(ac0, ac1, schema=schema, exclude_schema=exclude_schema)
  File "/home/st/p/python/migra/venv/lib/python3.8/site-packages/migra/migra.py", line 33, in __init__
    self.changes.i_target = get_inspector(
  File "/home/st/p/python/migra/venv/lib/python3.8/site-packages/schemainspect/get.py", line 20, in get_inspector
    inspected = ic(c)
  File "/home/st/p/python/migra/venv/lib/python3.8/site-packages/schemainspect/pg/obj.py", line 1041, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/home/st/p/python/migra/venv/lib/python3.8/site-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/home/st/p/python/migra/venv/lib/python3.8/site-packages/schemainspect/pg/obj.py", line 1058, in load_all
    self.load_deps()
  File "/home/st/p/python/migra/venv/lib/python3.8/site-packages/schemainspect/pg/obj.py", line 1133, in load_deps
    self.selectables[x_dependent_on].dependents.append(x)
KeyError: '"public"."geometry_dump"'
</pre>
</details>

"geometry_dump" is the postgis type that describes the records returned by `ST_Dump`.

[1]: http://postgis.net/docs/ST_Dump.html

**Comment by trendels** [comment]
I looked into it a little bit more and it seems like the join in  https://github.com/djrobstep/schemainspect/blob/master/schemainspect/pg/sql/deps.sql to filter out objects owned by extensions does not work for composite types. When I run the relevant part against the schema above, none of the types (`kind = 'c'`) have an `extension_objid`:

```
b=# with things1 as (
    select
        oid as objid,
        relnamespace as namespace,
        relname as name,
        relkind as kind
    from pg_class
    where oid not in (
        select ftrelid from pg_foreign_table
    )
), extension_objids as (
    select
        objid as extension_objid
    from
        pg_depend d
    where
        d.refclassid = 'pg_extension'::regclass
)
select
    objid,
    kind,
    n.nspname as schema,
    name,
    extension_objid
from things1 t
    join pg_namespace n on t.namespace = n.oid
    left join extension_objids on t.objid = extension_objids.extension_objid
where
    kind in ('r', 'v', 'm', 'c', 'f') and
    nspname not in ('pg_internal', 'pg_catalog', 'information_schema', 'pg_toast')
    and nspname not like 'pg_temp_%' and nspname not like 'pg_toast_temp_%'
;
 objid  | kind | schema |       name        | extension_objid 
--------+------+--------+-------------------+-----------------
 495635 | r    | public | spatial_ref_sys   |          495635
 495969 | v    | public | geography_columns |          495969
 496088 | v    | public | geometry_columns  |          496088
 496685 | v    | public | raster_columns    |          496685
 496694 | v    | public | raster_overviews  |          496694
 496136 | c    | public | rastbandarg       |               Ø
 496551 | c    | public | agg_samealignment |               Ø
 496210 | c    | public | agg_count         |               Ø
 495628 | c    | public | geometry_dump     |               Ø
 496139 | c    | public | geomval           |               Ø
 496717 | v    | public | v                 |               Ø
 496711 | r    | public | t                 |               Ø
 496606 | c    | public | unionarg          |               Ø
 495734 | c    | public | valid_detail      |               Ø
 496310 | c    | public | reclassarg        |               Ø
 496166 | c    | public | addbandarg        |               Ø
 496179 | c    | public | summarystats      |               Ø
```

After poking around in the Postgres docs I found this in the [`pg_types`][1] description:
> `typrelid`: If this is a composite type (see typtype), then this column points to the pg_class entry that defines the corresponding table. (For a free-standing composite type, the pg_class entry doesn't really represent a table, but it is needed anyway for the type's pg_attribute entries to link to.) 

It seems to be possible to get the extension object id by looking up the composite type via the `typrelid` column in `pg_types`:

```
b=# select t.typname, t.typrelid, t.oid, d.objid as extension_objid, e.extname
from pg_type t
    join pg_depend d on t.oid = d.objid
    join pg_extension e on d.deptype = 'e' and d.refobjid = e.oid
where d.refclassid = 'pg_extension'::regclass
  and t.typrelid = 495628;
    typname    | typrelid |  oid   | extension_objid | extname 
---------------+----------+--------+-----------------+---------
 geometry_dump |   495628 | 495630 |          495630 | postgis

```

I'm not sure I understand what exactly the difference is between the `typrelid` and `oid` of the type here to be honest, this was mostly trial and error, but maybe it helps.

[1]: https://www.postgresql.org/docs/12/catalog-pg-type.html

**Comment by djrobstep** [comment]
Thanks again for filing this, and particularly thank you for the comprehensive description. I've just pushed out a fix for this, it should get released in a few minutes.

**Comment by trendels** [comment]
Thanks for the quick fix!
