### ISSUE TITLE
schemainspect can't handle multiple tables having constraints with the same name

### ISSUE THREAD

**Issue by BenSjoberg** [djrobstep/schemainspect#7]
First off, I'm not a Python dev, so sorry if I get some terms wrong.

While testing [migra](https://github.com/djrobstep/migra), which uses schemainspect, I discovered diffs weren't being generated correctly when I modified certain constraints.

I managed to track this down to an issue with schemainspect - when you call `get_inspector()`, the `constraints` property is an OrderedDict with keys formatted as `"schema_name"."constraint_name"`. Formatting the key this way means you can't have two constraints in different tables with the same name. Postgres actually allows this - constraint names only have to be unique per-table, not per-schema (unlike index names).

My hacky solution is to patch schemainspect/pg/\_\_init__.py to change the key format to `"schema_name"."table_name"."constraint_name"`. This causes migra to work correctly on the schemas I'm testing it with. [Here's my patch.](https://github.com/djrobstep/schemainspect/files/1884901/schemainspect_patch.txt) I'm hesitant to open a pull request for it since I've never used schemainspect other than as a dependency of migra, so I'm not sure if this is considered a breaking change, or if it might cause other issues.

**Comment by djrobstep** [comment]
Hey, thanks heaps for reporting this!

Until you posted this I wasn't aware the same constraint name could be used per-table.

Your suggested fix seems sound, only thing I would suggest is to change the key by overriding the `quoted_full_name` property of `InspectedConstraint` to return the corrected `schema.table.name` form.

This shouldn't break anything, only fix it. Want to put together a pull request?

**Comment by BenSjoberg** [comment]
No problem - I actually didn't know this was allowed either until I ran across this issue! I just happened to be testing migra on various schemas in my company's code repo and discovered it.

I overrode the quoted_full_name property like you suggested and opened PR #8
